spring:
  application:
    name: experience

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50 MB

springdoc:
  default-produces-media-type: application/json

server:
  port: 8088
  servlet:
    context-path: /api/v1/