spring:
  application:
    name: experience

  datasource:
    url: jdbc:postgresql://localhost:5432/experience_db
    username: dbu_abdelqodous
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: abdelqodous
    password: P@ssw0rd
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        time: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: Rf1c8x+ZZY2KTSIVutZgHfhWLV6bIY2IMk79FbEzkCo/kT2y0MrL6af8sXP2nBfIg50gBs96FFA97T04TJ5OgA==
      expiration: 86400
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
